### ISSUE TITLE
Check `origin` in `do_remove_origin()`

### ISSUE THREAD

**Issue by NachoPal** [Watr-Protocol/watr#51]
`T::GovernanceOrigin::ensure_origin(origin)?;` should be removed from inside `do_remove_issuer()` since it will be called also from `remove_did()`.

It should check if origin is `GovernanceOrigin`, if it is not then it should check if the origin is the `controller` of the `Issuer`.

**Comment by NachoPal** [comment]
This has not been actually addressed. Do remove issuer should receive `origin` as argument and pass the `ensure_governance_or_controller` where if not Governance it should be Issuer's controller.

**Comment by peterwht** [comment]
I am a bit hesitant to do this as, to me, it seems like its adding unnecessary complexity / redundant code. Here is my reasoning:

- **First execution flow**: `fn remove_issuer` can ONLY be called by Governance. Meaning, `GovernanceOrigin` will have already been checked by the time `do_remove_issuer` is called. 
-  **Second execution flow**: The only other routes to reach `do_remove_issuer` are from `remove_did` and `force_remove_did`, which both call `do_remove_did`
    - `do_remove_did` calls `ensure_governance_or_controller` before calling `do_remove_issuer`.
 
So, from the routes available to `do_remove_issuer`, `GovernanceOrigin` is already checked OR, `ensure_governance_or_controller` is called.

**Comment by NachoPal** [comment]
> I am a bit hesitant to do this as, to me, it seems like its adding unnecessary complexity / redundant code. Here is my reasoning:
> 
> * **First execution flow**: `fn remove_issuer` can ONLY be called by Governance. Meaning, `GovernanceOrigin` will have already been checked by the time `do_remove_issuer` is called.
> * **Second execution flow**: The only other routes to reach `do_remove_issuer` are from `remove_did` and `force_remove_did`, which both call `do_remove_did`
>   
>   * `do_remove_did` calls `ensure_governance_or_controller` before calling `do_remove_issuer`.
> 
> So, from the routes available to `do_remove_issuer`, `GovernanceOrigin` is already checked OR, `ensure_governance_or_controller` is called.

Yeah, you are right. I didn't like to have a helper where something is removed without a checking inside it, but truth is there are already others such as `do_remove_did_services` without it.

Closing it.
