### ISSUE TITLE
Add TUSD precompile check

### ISSUE THREAD

**Issue by peterwht** [Watr-Protocol/watr#87]
`ensure_tusd_contract_origin` before calling TUSD xc-20.

**Comment by niall-watr** [comment]
Are we adding the precompiles here or would it make more sense to have them in a standalone repo?

**Comment by peterwht** [comment]
I realized a cleaner way to do it (not fully tested yet). But the idea is to leave the XC-20 precompile unchanged (imported from the astar-frame fork). In `runtime/devnet/precompiles.rs` we will check the calling address and only dispatch to the precompile if it is the contract address. 

I started working on this here: https://github.com/Watr-Protocol/watr/blob/add-tusd-precompile/runtime/devnet/src/precompiles.rs#L108

With this method, there will be no new precompile, and makes maintenance much easier.

**Comment by niall-watr** [comment]
Much neater, is that the extent of the precompile changes needed?

**Comment by tt-krzysztof** [comment]
I believe we also considered exposing additional methods from the asset pallet: `force_transfer`, possibly also `freeze` and `thaw`.

**Comment by peterwht** [comment]
Hi @tt-krzysztof, we added those [here](https://github.com/Watr-Protocol/astar-frame/blob/polkadot-v0.9.30/precompiles/assets-erc20/src/lib.rs). See this commit to see what additional functions were added: https://github.com/Watr-Protocol/astar-frame/commit/9051e5129f988b2cbb7f663e0384ba787085f78c

So, we have the precompile origin check, and several asset management functions that can be dispatched through the contract. Including `freeze` and `thaw`.

**Comment by peterwht** [comment]
Closed via https://github.com/Watr-Protocol/watr/pull/91
