### ISSUE TITLE
Update methods exposed from the asset precompile

### ISSUE THREAD

**Issue by tt-krzysztof** [Watr-Protocol/watr#97]
For the TUSD ERC20 contract delegating to the native asset precompile we need the following set of administrative methods:

1. `force_transfer`
2. `freeze`
3. `thaw`
4. `freeze_asset`
5. `thaw_asset`

Therefore, `force_transfer` is missing among currently exposed methods. 

On the other hand, we don't see a use-case where `transfer_ownership` or
`set_team` could be required. Those 2 methods can always me called by the asset owner. I imagine that in the mainnet setup the owner would be a multisig or a governance-controlled account.

**Comment by niall-watr** [comment]
This has been added as of this afternoon, pending final testing I'll deploy the runtime update on devnet tomorrow
